# Generated by Django 5.0.3 on 2024-03-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_data_delete_student_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='student_data',
        ),
    ]
